import 'package:cell_forensic/ar/ar_asset_definition.dart';

/// Full inventory of on-disk GLB assets (E0-01). Generated from
/// `docs/asset_inventory.csv` — re-run the inventory script after adding files.
class ArAssetManifest {
  const ArAssetManifest._();

  static const allAssets = <ArAssetDefinition>[
    ArAssetDefinition(
      code: 'mejalab',
      flutterAssetPath: 'assets/ar_models/Meja/MejaLab.glb',
      format: 'GLB',
      sizeBytes: 22416,
      triangleCount: 374,
      materialCount: 3,
      textureImageCount: 0,
      keyNodes: ['Cube.001'],
      status: 'ready',
      preloadGroup: 'lab',
      notes: 'no animation clips; nodes mostly Blender defaults (Cube/Sphere)',
    ),
    ArAssetDefinition(
      code: 'tempatuji',
      flutterAssetPath: 'assets/ar_models/Meja/TempatUji.glb',
      format: 'GLB',
      sizeBytes: 31148,
      triangleCount: 1216,
      materialCount: 1,
      textureImageCount: 0,
      keyNodes: ['Cube.002'],
      status: 'ready',
      preloadGroup: 'lab',
      notes: 'no animation clips; nodes mostly Blender defaults (Cube/Sphere)',
    ),
    ArAssetDefinition(
      code: 'rantaiprotein',
      flutterAssetPath: 'assets/ar_models/SelHewan/RantaiProtein/RantaiProtein.glb',
      format: 'GLB',
      sizeBytes: 3648744,
      triangleCount: 122256,
      materialCount: 3,
      textureImageCount: 0,
      keyNodes: ['NurbsPath', 'NurbsPath.001', 'Cube.063', 'Cube.064', 'Cube.065', 'Cube.066', 'Cube.067', 'Cube.068'],
      status: 'ready',
      preloadGroup: 'sample_b_detail',
      notes: 'no animation clips; nodes mostly Blender defaults (Cube/Sphere)',
    ),
    ArAssetDefinition(
      code: 'selhewanbroken_plus_meja',
      flutterAssetPath: 'assets/ar_models/SelHewan/SelHewanBroken+Meja.glb',
      format: 'GLB',
      sizeBytes: 1549004,
      triangleCount: 62334,
      materialCount: 17,
      textureImageCount: 0,
      keyNodes: ['Cube.001', 'Cube.002', 'Cube.213'],
      status: 'fix',
      preloadGroup: 'lab',
      notes: 'filename spaces/+ — avoid in Model Viewer URL; no animation clips; nodes mostly Blender defaults (Cube/Sphere)',
    ),
    ArAssetDefinition(
      code: 'selhewanbroken',
      flutterAssetPath: 'assets/ar_models/SelHewan/SelHewanBroken.glb',
      format: 'GLB',
      sizeBytes: 1295868,
      triangleCount: 59304,
      materialCount: 13,
      textureImageCount: 0,
      keyNodes: ['Plane.007', 'Plane.008', 'Plane.009', 'Plane.010', 'Plane.011', 'Plane.013', 'Plane.014', 'Plane.015'],
      status: 'ready',
      preloadGroup: 'sample_b',
      notes: 'no animation clips',
    ),
    ArAssetDefinition(
      code: 'dindingsel',
      flutterAssetPath: 'assets/ar_models/SelTumbuhan/DindingSel.glb',
      format: 'GLB',
      sizeBytes: 9744,
      triangleCount: 200,
      materialCount: 1,
      textureImageCount: 0,
      keyNodes: ['DindingSel', 'DindingSel.001', 'DindingSel.002'],
      status: 'ready',
      preloadGroup: 'sample_a',
      notes: 'no animation clips',
    ),
    ArAssetDefinition(
      code: 'kloroplas',
      flutterAssetPath: 'assets/ar_models/SelTumbuhan/Kloroplas.glb',
      format: 'GLB',
      sizeBytes: 4038556,
      triangleCount: 151056,
      materialCount: 4,
      textureImageCount: 0,
      keyNodes: ['Cube.022', 'Cube.023', 'Cube.024', 'Cube.025', 'Cube.026', 'Cube.027', 'Cube.028', 'Cube.029'],
      status: 'ready',
      preloadGroup: 'sample_a',
      notes: 'no animation clips; nodes mostly Blender defaults (Cube/Sphere)',
    ),
    ArAssetDefinition(
      code: 'mitokondria',
      flutterAssetPath: 'assets/ar_models/SelTumbuhan/Mitokondria.glb',
      format: 'GLB',
      sizeBytes: 555768,
      triangleCount: 18144,
      materialCount: 1,
      textureImageCount: 0,
      keyNodes: ['Cube.018', 'Cube.016', 'Cube.019', 'Cube.020', 'Cube.069', 'Cube.080', 'Cube.082', 'Cube.1549'],
      status: 'ready',
      preloadGroup: 'sample_a',
      notes: 'no animation clips; nodes mostly Blender defaults (Cube/Sphere)',
    ),
    ArAssetDefinition(
      code: 'nukleus',
      flutterAssetPath: 'assets/ar_models/SelTumbuhan/Nukleus.glb',
      format: 'GLB',
      sizeBytes: 3101792,
      triangleCount: 110832,
      materialCount: 2,
      textureImageCount: 0,
      keyNodes: ['Sphere.014', 'Sphere.015', 'Sphere.016', 'Sphere.017', 'Sphere.018', 'Sphere.019', 'Sphere.020', 'Sphere.076'],
      status: 'ready',
      preloadGroup: 'sample_a',
      notes: 'no animation clips; nodes mostly Blender defaults (Cube/Sphere)',
    ),
    ArAssetDefinition(
      code: 'seltumbuhanrework_all_plus_meja',
      flutterAssetPath: 'assets/ar_models/SelTumbuhan/SelTumbuhanRework_All+Meja.glb',
      format: 'GLB',
      sizeBytes: 17577024,
      triangleCount: 516354,
      materialCount: 15,
      textureImageCount: 0,
      keyNodes: ['DindingSel'],
      status: 'fix',
      preloadGroup: 'lab',
      notes: 'size>8MB — preload hati-hati; filename spaces/+ — avoid in Model Viewer URL; high tris (516354); no animation clips',
    ),
    ArAssetDefinition(
      code: 'seltumbuhanrework_allinone',
      flutterAssetPath: 'assets/ar_models/SelTumbuhan/SelTumbuhanRework_AllInOne.glb',
      format: 'GLB',
      sizeBytes: 7962284,
      triangleCount: 287652,
      materialCount: 11,
      textureImageCount: 0,
      keyNodes: ['DindingSel', 'Vakuola Main', 'DindingSel.001', 'Vakuola Main.001', 'DindingSel.002', 'Vakuola Main.002'],
      status: 'fix',
      preloadGroup: 'sample_a',
      notes: 'high tris (287652); no animation clips',
    ),
    ArAssetDefinition(
      code: 'dindingsel_solo',
      flutterAssetPath: 'assets/ar_models/SelTumbuhan/SelTumbuhhanSolo/DindingSel_Solo.glb',
      format: 'GLB',
      sizeBytes: 19652,
      triangleCount: 400,
      materialCount: 1,
      textureImageCount: 0,
      keyNodes: ['DindingSel', 'DindingSel.001', 'DindingSel.002'],
      status: 'ready',
      preloadGroup: 'sample_a_solo',
      notes: 'no animation clips',
    ),
    ArAssetDefinition(
      code: 'klooroplas_solo',
      flutterAssetPath: 'assets/ar_models/SelTumbuhan/SelTumbuhhanSolo/KlooroPlas_Solo.glb',
      format: 'GLB',
      sizeBytes: 2030960,
      triangleCount: 78480,
      materialCount: 4,
      textureImageCount: 0,
      keyNodes: ['Cube.022', 'Cube.023', 'Cube.024', 'Cube.025', 'Cube.026', 'Cube.027', 'Cube.028', 'Cube.029'],
      status: 'ready',
      preloadGroup: 'sample_a_solo',
      notes: 'no animation clips; nodes mostly Blender defaults (Cube/Sphere)',
    ),
    ArAssetDefinition(
      code: 'mitokondria_solo',
      flutterAssetPath: 'assets/ar_models/SelTumbuhan/SelTumbuhhanSolo/Mitokondria_Solo.glb',
      format: 'GLB',
      sizeBytes: 189096,
      triangleCount: 6048,
      materialCount: 1,
      textureImageCount: 0,
      keyNodes: ['Cube.018', 'Cube.016', 'Cube.019', 'Cube.020', 'Cube.069', 'Cube.080', 'Cube.082'],
      status: 'ready',
      preloadGroup: 'sample_a_solo',
      notes: 'no animation clips; nodes mostly Blender defaults (Cube/Sphere)',
    ),
    ArAssetDefinition(
      code: 'nukleus_solo',
      flutterAssetPath: 'assets/ar_models/SelTumbuhan/SelTumbuhhanSolo/Nukleus_Solo.glb',
      format: 'GLB',
      sizeBytes: 1191460,
      triangleCount: 37296,
      materialCount: 2,
      textureImageCount: 0,
      keyNodes: ['Sphere.014', 'Sphere.015', 'Sphere.016', 'Sphere.017', 'Sphere.018', 'Sphere.019', 'Sphere.020'],
      status: 'ready',
      preloadGroup: 'sample_a_solo',
      notes: 'no animation clips; nodes mostly Blender defaults (Cube/Sphere)',
    ),
    ArAssetDefinition(
      code: 'sitoplasma_solo',
      flutterAssetPath: 'assets/ar_models/SelTumbuhan/SelTumbuhhanSolo/Sitoplasma_Solo.glb',
      format: 'GLB',
      sizeBytes: 76620,
      triangleCount: 3308,
      materialCount: 2,
      textureImageCount: 0,
      keyNodes: ['Cube.004', 'Cube.007'],
      status: 'ready',
      preloadGroup: 'sample_a_solo',
      notes: 'no animation clips; nodes mostly Blender defaults (Cube/Sphere)',
    ),
    ArAssetDefinition(
      code: 'vakolakecil_solo',
      flutterAssetPath: 'assets/ar_models/SelTumbuhan/SelTumbuhhanSolo/VakolaKecil_Solo.glb',
      format: 'GLB',
      sizeBytes: 18508,
      triangleCount: 528,
      materialCount: 1,
      textureImageCount: 0,
      keyNodes: ['Sphere.013', 'Sphere.021', 'Sphere.022', 'Sphere.024', 'Sphere.025', 'Sphere.026', 'Sphere.028', 'Sphere.029'],
      status: 'ready',
      preloadGroup: 'sample_a_solo',
      notes: 'no animation clips; nodes mostly Blender defaults (Cube/Sphere)',
    ),
    ArAssetDefinition(
      code: 'vakolamain_solo',
      flutterAssetPath: 'assets/ar_models/SelTumbuhan/SelTumbuhhanSolo/VakolaMain_Solo.glb',
      format: 'GLB',
      sizeBytes: 80424,
      triangleCount: 3584,
      materialCount: 1,
      textureImageCount: 0,
      keyNodes: ['Vakuola Main'],
      status: 'ready',
      preloadGroup: 'sample_a_solo',
      notes: 'no animation clips',
    ),
    ArAssetDefinition(
      code: 'sitoplasma',
      flutterAssetPath: 'assets/ar_models/SelTumbuhan/Sitoplasma.glb',
      format: 'GLB',
      sizeBytes: 76904,
      triangleCount: 3308,
      materialCount: 2,
      textureImageCount: 0,
      keyNodes: ['Cube.004', 'Cube.007', 'Cube.1556', 'Cube.1557', 'Cube.2033', 'Cube.2034'],
      status: 'ready',
      preloadGroup: 'sample_a',
      notes: 'no animation clips; nodes mostly Blender defaults (Cube/Sphere)',
    ),
    ArAssetDefinition(
      code: 'vakuola_kecil',
      flutterAssetPath: 'assets/ar_models/SelTumbuhan/vakuola Kecil.glb',
      format: 'GLB',
      sizeBytes: 25976,
      triangleCount: 528,
      materialCount: 1,
      textureImageCount: 0,
      keyNodes: ['Sphere.013', 'Sphere.021', 'Sphere.022', 'Sphere.024', 'Sphere.025', 'Sphere.026', 'Sphere.028', 'Sphere.029'],
      status: 'fix',
      preloadGroup: 'sample_a',
      notes: 'filename spaces/+ — avoid in Model Viewer URL; no animation clips; nodes mostly Blender defaults (Cube/Sphere)',
    ),
    ArAssetDefinition(
      code: 'vakuola_main',
      flutterAssetPath: 'assets/ar_models/SelTumbuhan/vakuola Main.glb',
      format: 'GLB',
      sizeBytes: 80900,
      triangleCount: 3584,
      materialCount: 1,
      textureImageCount: 0,
      keyNodes: ['Vakuola Main', 'Vakuola Main.001', 'Vakuola Main.002'],
      status: 'fix',
      preloadGroup: 'sample_a',
      notes: 'filename spaces/+ — avoid in Model Viewer URL; no animation clips',
    ),
    ArAssetDefinition(
      code: 'mejalab_putih',
      flutterAssetPath: 'assets/ar_models/Meja/MejaLab_Putih.glb',
      format: 'GLB',
      sizeBytes: 21964,
      triangleCount: 0,
      materialCount: 1,
      textureImageCount: 0,
      keyNodes: const <String>[],
      status: 'ready',
      preloadGroup: 'lab',
      notes: 'Active lab table (white) used by ArAssetRegistry.mejaLab',
    ),
    ArAssetDefinition(
      code: 'selhewanbroken_newexport',
      flutterAssetPath:
          'assets/ar_models/SelHewan/SelHewanBroken_NewExport 2.glb',
      format: 'GLB',
      sizeBytes: 1238248,
      triangleCount: 0,
      materialCount: 1,
      textureImageCount: 0,
      keyNodes: const <String>[],
      status: 'ready',
      preloadGroup: 'sample_b',
      notes: 'Active Sampel B — ArAssetRegistry.sampleB',
    ),
    ArAssetDefinition(
      code: 'seltumbuhan_export_1',
      flutterAssetPath:
          'assets/ar_models/SelTumbuhan/SelTumbuhanRework_Export_1_normal_color.glb',
      format: 'GLB',
      sizeBytes: 7464248,
      triangleCount: 0,
      materialCount: 1,
      textureImageCount: 0,
      keyNodes: const <String>[],
      status: 'ready',
      preloadGroup: 'sample_a',
      notes: 'Damaged Sampel A — ArAssetRegistry.sampleADamaged (no spaces)',
    ),
    ArAssetDefinition(
      code: 'seltumbuhan_export_2',
      flutterAssetPath:
          'assets/ar_models/SelTumbuhan/SelTumbuhanRework_Export_2_normal_color.glb',
      format: 'GLB',
      sizeBytes: 14779308,
      triangleCount: 0,
      materialCount: 1,
      textureImageCount: 0,
      keyNodes: const <String>[],
      status: 'ready',
      preloadGroup: 'sample_a',
      notes: 'Intact Sampel A — ArAssetRegistry.sampleA (no spaces)',
    ),
  ];

  static List<ArAssetDefinition> byStatus(String status) =>
      allAssets.where((a) => a.status == status).toList();

  static List<ArAssetDefinition> byPreloadGroup(String group) =>
      allAssets.where((a) => a.preloadGroup == group).toList();

  static ArAssetDefinition? byPath(String path) {
    for (final asset in allAssets) {
      if (asset.flutterAssetPath == path) return asset;
    }
    return null;
  }
}

